import { useState } from 'react';

export default function Admin() {
  const [cities, setCities] = useState('');
  const [qr, setQr]   = useState(null);

  const bulkCities = () => {
    const list = cities.split('\n').map(l => l.trim()).filter(Boolean);
    alert(`Imported ${list.length} cities`);
  };

  const saveQr = (e) => {
    const file = e.target.files[0];
    if (file) setQr(URL.createObjectURL(file));
    alert('QR uploaded');
  };

  return (
    <div style={{padding:40,fontFamily:'Arial'}}>
      <h1>Admin Panel – بلخدمة</h1>

      <h2>1. Cities (Bulk)</h2>
      <textarea rows="10" cols="60" placeholder="Achrafieh,أشرفية,Beirut&#10;Aley,عاليه,Mount Lebanon&#10;..." value={cities} onChange={(e)=>setCities(e.target.value)} />
      <br/>
      <button onClick={bulkCities}>Import Cities</button>

      <h2>2. Categories</h2>

<h3>On-Site Services</h3>
<label><input type="checkbox" defaultChecked /> Plumbing</label><br/>
<label><input type="checkbox" defaultChecked /> Electricity</label><br/>
<label><input type="checkbox" defaultChecked /> Painting</label><br/>
<label><input type="checkbox" defaultChecked /> Carpentry</label><br/>
<label><input type="checkbox" defaultChecked /> A/C Maintenance & Cleaning</label><br/>
<label><input type="checkbox" defaultChecked /> Satellite & TV Installation</label><br/>
<label><input type="checkbox" defaultChecked /> Internet & Wi-Fi Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Home Deep Cleaning</label><br/>
<label><input type="checkbox" defaultChecked /> Office Cleaning</label><br/>
<label><input type="checkbox" defaultChecked /> Car Wash (Mobile)</label><br/>
<label><input type="checkbox" defaultChecked /> Private Tutor (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> Babysitting & Child Care</label><br/>
<label><input type="checkbox" defaultChecked /> Pet Care & Dog Walking</label><br/>
<label><input type="checkbox" defaultChecked /> Furniture Assembly</label><br/>
<label><input type="checkbox" defaultChecked /> Curtain & Blinds Installation</label><br/>
<label><input type="checkbox" defaultChecked /> Wallpaper & Vinyl Wrap</label><br/>
<label><input type="checkbox" defaultChecked /> Plaster & Gypsum Board</label><br/>
<label><input type="checkbox" defaultChecked /> Tiling & Marble Works</label><br/>
<label><input type="checkbox" defaultChecked /> Flooring (Parquet, Laminate, Vinyl)</label><br/>
<label><input type="checkbox" defaultChecked /> Swimming-Pool Cleaning</label><br/>
<label><input type="checkbox" defaultChecked /> Gardening & Landscaping</label><br/>
<label><input type="checkbox" defaultChecked /> Glass & Aluminium Works</label><br/>
<label><input type="checkbox" defaultChecked /> CCTV & Security Cameras</label><br/>
<label><input type="checkbox" defaultChecked /> Locksmith & Key Duplication</label><br/>
<label><input type="checkbox" defaultChecked /> Appliance Repair (Fridge, Washer, etc.)</label><br/>
<label><input type="checkbox" defaultChecked /> Water-Heater Repair</label><br/>
<label><input type="checkbox" defaultChecked /> Carpet & Sofa Cleaning</label><br/>
<label><input type="checkbox" defaultChecked /> Pest Control (Cockroaches, Rats, Termites)</label><br/>
<label><input type="checkbox" defaultChecked /> Moving & Transport</label><br/>
<label><input type="checkbox" defaultChecked /> Handyman (General Fixes)</label><br/>
<label><input type="checkbox" defaultChecked /> Generator Maintenance</label><br/>
<label><input type="checkbox" defaultChecked /> Solar-Water-Heater Service</label><br/>
<label><input type="checkbox" defaultChecked /> Roofing & Leak Fix</label><br/>
<label><input type="checkbox" defaultChecked /> Junk Removal & Disposal</label><br/>
<label><input type="checkbox" defaultChecked /> Furniture-Wrapping (Moving)</label><br/>
<label><input type="checkbox" defaultChecked /> AC-Duct Cleaning</label><br/>
<label><input type="checkbox" defaultChecked /> Mattress Cleaning</label><br/>
<label><input type="checkbox" defaultChecked /> Kitchen-Exhaust Hood Cleaning</label><br/>
<label><input type="checkbox" defaultChecked /> Septic-Tank Cleaning</label><br/>
<label><input type="checkbox" defaultChecked /> Mold Removal & Waterproofing</label><br/>
<label><input type="checkbox" defaultChecked /> Stair-Lift Installation</label><br/>
<label><input type="checkbox" defaultChecked /> Smart-Lock Installation</label><br/>
<label><input type="checkbox" defaultChecked /> Video-Doorbell Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Home-Cinema Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Coffee-Machine Repair</label><br/>
<label><input type="checkbox" defaultChecked /> Wine-Cellar Cooling Unit</label><br/>
<label><input type="checkbox" defaultChecked /> Safe-Opening & Repair</label><br/>
<label><input type="checkbox" defaultChecked /> Basketball-Hoop Assembly</label><br/>
<label><input type="checkbox" defaultChecked /> Trampoline Assembly</label><br/>
<label><input type="checkbox" defaultChecked /> Pool-Table Assembly</label><br/>
<label><input type="checkbox" defaultChecked /> Treadmill-Assembly & Repair</label><br/>
<label><input type="checkbox" defaultChecked /> Piano-Movers</label><br/>
<label><input type="checkbox" defaultChecked /> Art & Antique Handling</label><br/>
<label><input type="checkbox" defaultChecked /> Party-Tent Rental & Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Balloon-Decoration</label><br/>
<label><input type="checkbox" defaultChecked /> Chocolate-Fountain Rental</label><br/>
<label><input type="checkbox" defaultChecked /> BBQ-Grill Setup & Clean</label><br/>
<label><input type="checkbox" defaultChecked /> Personal-Chef (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> Catering (Small Events)</label><br/>
<label><input type="checkbox" defaultChecked /> Birthday-Cake Delivery</label><br/>
<label><input type="checkbox" defaultChecked /> Healthy-Meal-Prep Delivery</label><br/>
<label><input type="checkbox" defaultChecked /> Nurse-Home Visit</label><br/>
<label><input type="checkbox" defaultChecked /> Elderly-Care (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> Newborn-Care Specialist</label><br/>
<label><input type="checkbox" defaultChecked /> Lactation-Consultant (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> Massage-Therapist (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> Hairdresser (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> Makeup-Artist (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> Henna-Artist (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> Photographer (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> Drone-Photography</label><br/>
<label><input type="checkbox" defaultChecked /> Photo-Booth Rental</label><br/>
<label><input type="checkbox" defaultChecked /> DJ-for-House-Party</label><br/>
<label><input type="checkbox" defaultChecked /> Kids-Entertainment (Clown)</label><br/>
<label><input type="checkbox" defaultChecked /> Face-Painting</label><br/>
<label><input type="checkbox" defaultChecked /> Bouncy-Castle Rental</label><br/>
<label><input type="checkbox" defaultChecked /> Mobile-Petting-Zoo</label><br/>
<label><input type="checkbox" defaultChecked /> Florist & Bouquet-Delivery</label><br/>
<label><input type="checkbox" defaultChecked /> Tailor (Home Visit)</label><br/>
<label><input type="checkbox" defaultChecked /> Shoe-Repair (Pick-up)</label><br/>
<label><input type="checkbox" defaultChecked /> Watch-Battery Replacement</label><br/>
<label><input type="checkbox" defaultChecked /> Phone-Screen Repair</label><br/>
<label><input type="checkbox" defaultChecked /> Tablet-Repair (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> Laptop-Repair (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> Console-Repair (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> EV-Charger Installation</label><br/>
<label><input type="checkbox" defaultChecked /> Car-Audio Install</label><br/>
<label><input type="checkbox" defaultChecked /> Window-Tinting</label><br/>
<label><input type="checkbox" defaultChecked /> Towing-Service</label><br/>
<label><input type="checkbox" defaultChecked /> Battery-Replacement</label><br/>
<label><input type="checkbox" defaultChecked /> Tyre-Change (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> Oil-Change (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> Brake-Pad Change</label><br/>
<label><input type="checkbox" defaultChecked /> Pre-Purchase Car Inspection</label><br/>
<label><input type="checkbox" defaultChecked /> Driving-Instructor (Home Pick-up)</label><br/>
<label><input type="checkbox" defaultChecked /> Boat-Cleaning</label><br/>
<label><input type="checkbox" defaultChecked /> Jet-Ski Service</label><br/>
<label><input type="checkbox" defaultChecked /> Pool-Table Felt-Change</label><br/>
<label><input type="checkbox" defaultChecked /> Safe-Moving & Installation</label><br/>
<label><input type="checkbox" defaultChecked /> Mystery-Shopper Service</label><br/>
<label><input type="checkbox" defaultChecked /> Personal-Assistant (Daily)</label><br/>
<label><input type="checkbox" defaultChecked /> Butler Service</label><br/>
<label><input type="checkbox" defaultChecked /> Private-Chef (Daily)</label><br/>
<label><input type="checkbox" defaultChecked /> Nutrition-Coach</label><br/>
<label><input type="checkbox" defaultChecked /> Fitness-Trainer (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> Yoga-Instructor (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> Pilates-Instructor (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> Life-Coach (Home)</label><br/>
<label><input type="checkbox" defaultChecked /> Career-Counselling (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Interview-Prep Coach</label><br/>
<label><input type="checkbox" defaultChecked /> CV/Resume Writing</label><br/>
<label><input type="checkbox" defaultChecked /> LinkedIn-Makeover</label><br/>
<label><input type="checkbox" defaultChecked /> Public-Speaking Coach</label><br/>
<label><input type="checkbox" defaultChecked /> Language-Conversation Partner</label><br/>
<label><input type="checkbox" defaultChecked /> Baby-Sleep-Trainer</label><br/>
<label><input type="checkbox" defaultChecked /> Colic-Consultant</label><br/>
<label><input type="checkbox" defaultChecked /> Postpartum-Doula</label><br/>
<label><input type="checkbox" defaultChecked /> Newborn-Photography</label><br/>
<label><input type="checkbox" defaultChecked /> Maternity-Photography</label><br/>
<label><input type="checkbox" defaultChecked /> Family-Photography</label><br/>
<label><input type="checkbox" defaultChecked /> Pet-Photography</label><br/>
<label><input type="checkbox" defaultChecked /> Product-Photography</label><br/>
<label><input type="checkbox" defaultChecked /> Food-Photography</label><br/>
<label><input type="checkbox" defaultChecked /> Real-Estate-Photography</label><br/>
<label><input type="checkbox" defaultChecked /> Event-Photography</label><br/>
<label><input type="checkbox" defaultChecked /> Wedding-Photography</label><br/>
<label><input type="checkbox" defaultChecked /> Engagement-Photography</label><br/>
<label><input type="checkbox" defaultChecked /> Birthday-Photography</label><br/>
<label><input type="checkbox" defaultChecked /> Corporate-Headshots</label><br/>
<label><input type="checkbox" defaultChecked /> Drone-Photography</label><br/>
<label><input type="checkbox" defaultChecked /> 360-Virtual-Tour</label><br/>
<label><input type="checkbox" defaultChecked /> Photo-Booth Rental</label><br/>
<label><input type="checkbox" defaultChecked /> Instant-Print Photo</label><br/>
<label><input type="checkbox" defaultChecked /> Video-Shooting</label><br/>
<label><input type="checkbox" defaultChecked /> Video-Editing</label><br/>
<label><input type="checkbox" defaultChecked /> Drone-Video</label><br/>
<label><input type="checkbox" defaultChecked /> Motion-Graphics</label><br/>
<label><input type="checkbox" defaultChecked /> Animation-2D</label><br/>
<label><input type="checkbox" defaultChecked /> Animation-3D</label><br/>
<label><input type="checkbox" defaultChecked /> Whiteboard-Animation</label><br/>
<label><input type="checkbox" defaultChecked /> Explainer-Video</label><br/>
<label><input type="checkbox" defaultChecked /> Promo-Video</label><br/>
<label><input type="checkbox" defaultChecked /> TikTok-Video Editing</label><br/>
<label><input type="checkbox" defaultChecked /> Reels-Editing</label><br/>
<label><input type="checkbox" defaultChecked /> YouTube-Channel Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Podcast-Editing</label><br/>
<label><input type="checkbox" defaultChecked /> Audio-Mastering</label><br/>
<label><input type="checkbox" defaultChecked /> Voice-Over Recording</label><br/>
<label><input type="checkbox" defaultChecked /> Jingle-Production</label><br/>
<label><input type="checkbox" defaultChecked /> Sound-Effects Design</label><br/>
<label><input type="checkbox" defaultChecked /> Music-Composition</label><br/>
<label><input type="checkbox" defaultChecked /> Song-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Ghost-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> eBook-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Blog-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Article-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Website-Content</label><br/>
<label><input type="checkbox" defaultChecked /> SEO-Content</label><br/>
<label><input type="checkbox" defaultChecked /> Copywriting</label><br/>
<label><input type="checkbox" defaultChecked /> Sales-Page Copy</label><br/>
<label><input type="checkbox" defaultChecked /> Email-Copywriting</label><br/>
<label><input type="checkbox" defaultChecked /> Newsletter-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Press-Release Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Speech-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Proofreading & Editing</label><br/>
<label><input type="checkbox" defaultChecked /> Translation</label><br/>
<label><input type="checkbox" defaultChecked /> Transcription</label><br/>
<label><input type="checkbox" defaultChecked /> Subtitling & Captioning</label><br/>
<label><input type="checkbox" defaultChecked /> NFT-Art Creation</label><br/>
<label><input type="checkbox" defaultChecked /> Crypto-Consultation</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Tutoring (All Subjects)</label><br/>
<label><input type="checkbox" defaultChecked /> Interview-Prep Coach</label><br/>
<label><input type="checkbox" defaultChecked /> CV/Resume Writing</label><br/>
<label><input type="checkbox" defaultChecked /> LinkedIn-Makeover</label><br/>
<label><input type="checkbox" defaultChecked /> Public-Speaking Coach</label><br/>
<label><input type="checkbox" defaultChecked /> Language-Conversation Partner</label><br/>

<h3>Online Services</h3>
<label><input type="checkbox" defaultChecked /> Graphic-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Logo-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Brand-Identity Design</label><br/>
<label><input type="checkbox" defaultChecked /> Web-Development</label><br/>
<label><input type="checkbox" defaultChecked /> App-Development</label><br/>
<label><input type="checkbox" defaultChecked /> E-Commerce Store Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Shopify-Build</label><br/>
<label><input type="checkbox" defaultChecked /> WooCommerce-Build</label><br/>
<label><input type="checkbox" defaultChecked /> Etsy-Store Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Amazon-FBA Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Dropshipping-Store Build</label><br/>
<label><input type="checkbox" defaultChecked /> SEO Services</label><br/>
<label><input type="checkbox" defaultChecked /> Social-Media Management</label><br/>
<label><input type="checkbox" defaultChecked /> Digital-Marketing</label><br/>
<label><input type="checkbox" defaultChecked /> Google-Ads Management</label><br/>
<label><input type="checkbox" defaultChecked /> Facebook-Ads Management</label><br/>
<label><input type="checkbox" defaultChecked /> Instagram-Ads Management</label><br/>
<label><input type="checkbox" defaultChecked /> TikTok-Ads Management</label><br/>
<label><input type="checkbox" defaultChecked /> Content-Creation</label><br/>
<label><input type="checkbox" defaultChecked /> Copywriting</label><br/>
<label><input type="checkbox" defaultChecked /> Email-Marketing</label><br/>
<label><input type="checkbox" defaultChecked /> Newsletter-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Blog-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Article-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Translation</label><br/>
<label><input type="checkbox" defaultChecked /> Transcription</label><br/>
<label><input type="checkbox" defaultChecked /> Subtitling & Captioning</label><br/>
<label><input type="checkbox" defaultChecked /> Voice-Over Recording</label><br/>
<label><input type="checkbox" defaultChecked /> Video-Editing</label><br/>
<label><input type="checkbox" defaultChecked /> Motion-Graphics</label><br/>
<label><input type="checkbox" defaultChecked /> Animation-2D</label><br/>
<label><input type="checkbox" defaultChecked /> Animation-3D</label><br/>
<label><input type="checkbox" defaultChecked /> Explainer-Video</label><br/>
<label><input type="checkbox" defaultChecked /> TikTok-Video Editing</label><br/>
<label><input type="checkbox" defaultChecked /> Reels-Editing</label><br/>
<label><input type="checkbox" defaultChecked /> YouTube-Channel Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Podcast-Editing</label><br/>
<label><input type="checkbox" defaultChecked /> Audio-Mastering</label><br/>
<label><input type="checkbox" defaultChecked /> Music-Composition</label><br/>
<label><input type="checkbox" defaultChecked /> Jingle-Production</label><br/>
<label><input type="checkbox" defaultChecked /> NFT-Art Creation</label><br/>
<label><input type="checkbox" defaultChecked /> Crypto-Consultation</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Tutoring (All Subjects)</label><br/>
<label><input type="checkbox" defaultChecked /> Coding-Bootcamp Mentor</label><br/>
<label><input type="checkbox" defaultChecked /> Web-Dev Mentor</label><br/>
<label><input type="checkbox" defaultChecked /> App-Dev Mentor</label><br/>
<label><input type="checkbox" defaultChecked /> Data-Science Mentor</label><br/>
<label><input type="checkbox" defaultChecked /> UX/UI Design Mentor</label><br/>
<label><input type="checkbox" defaultChecked /> Graphic-Design Mentor</label><br/>
<label><input type="checkbox" defaultChecked /> Interview-Prep Coach</label><br/>
<label><input type="checkbox" defaultChecked /> CV/Resume Writing</label><br/>
<label><input type="checkbox" defaultChecked /> LinkedIn-Makeover</label><br/>
<label><input type="checkbox" defaultChecked /> Public-Speaking Coach</label><br/>
<label><input type="checkbox" defaultChecked /> Language-Conversation Partner</label><br/>
<label><input type="checkbox" defaultChecked /> Business-Plan Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Pitch-Deck Creation</label><br/>
<label><input type="checkbox" defaultChecked /> Grant-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Policy-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Technical-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Medical-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Legal-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Research-Paper Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Thesis-Editing</label><br/>
<label><input type="checkbox" defaultChecked /> Dissertation-Coaching</label><br/>
<label><input type="checkbox" defaultChecked /> Data-Analysis (Excel, R, Python)</label><br/>
<label><input type="checkbox" defaultChecked /> Survey-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Market-Research Report</label><br/>
<label><input type="checkbox" defaultChecked /> Competitor-Analysis</label><br/>
<label><input type="checkbox" defaultChecked /> Brand-Strategy Consult</label><br/>
<label><input type="checkbox" defaultChecked /> Logo-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Brand-Identity Design</label><br/>
<label><input type="checkbox" defaultChecked /> Packaging-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Label-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Menu-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Brochure-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Flyer-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Poster-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Banner-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Infographic-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Presentation-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Report-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Print-Ready Files</label><br/>
<label><input type="checkbox" defaultChecked /> E-Book Formatting</label><br/>
<label><input type="checkbox" defaultChecked /> Kindle Formatting</label><br/>
<label><input type="checkbox" defaultChecked /> Amazon-KDP Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Shopify-Store Setup</label><br/>
<label><input type="checkbox" defaultChecked /> WooCommerce-Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Etsy-Store Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Amazon-FBA Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Dropshipping-Store Build</label><br/>
<label><input type="checkbox" defaultChecked /> Product-Listing Optimization</label><br/>
<label><input type="checkbox" defaultChecked /> Amazon-PPC Management</label><br/>
<label><input type="checkbox" defaultChecked /> Etsy-SEO</label><br/>
<label><input type="checkbox" defaultChecked /> eBay-Store Management</label><br/>
<label><input type="checkbox" defaultChecked /> Facebook-Shop Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Instagram-Shop Setup</label><br/>
<label><input type="checkbox" defaultChecked /> TikTok-Shop Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Google-Shopping Feed</label><br/>
<label><input type="checkbox" defaultChecked /> Conversion-Rate Optimization</label><br/>
<label><input type="checkbox" defaultChecked /> A/B Testing Consult</label><br/>
<label><input type="checkbox" defaultChecked /> Customer-Journey Mapping</label><br/>
<label><input type="checkbox" defaultChecked /> UX-Audit & Recommendations</label><br/>
<label><input type="checkbox" defaultChecked /> Accessibility-Audit (WCAG)</label><br/>
<label><input type="checkbox" defaultChecked /> Privacy-Policy Drafting</label><br/>
<label><input type="checkbox" defaultChecked /> Terms-of-Service Drafting</label><br/>
<label><input type="checkbox" defaultChecked /> Cookie-Policy Drafting</label><br/>
<label><input type="checkbox" defaultChecked /> Return-Policy Drafting</label><br/>
<label><input type="checkbox" defaultChecked /> Disclaimer Drafting</label><br/>
<label><input type="checkbox" defaultChecked /> EULA Drafting</label><br/>
<label><input type="checkbox" defaultChecked /> SLA Drafting</label><br/>
<label><input type="checkbox" defaultChecked /> Contract-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Agreement-Review</label><br/>
<label><input type="checkbox" defaultChecked /> Legal-Consultation (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Tax-Consultation (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Accounting-Books Cleanup</label><br/>
<label><input type="checkbox" defaultChecked /> Bookkeeping-Service</label><br/>
<label><input type="checkbox" defaultChecked /> Payroll-Processing</label><br/>
<label><input type="checkbox" defaultChecked /> Financial-Projection Model</label><br/>
<label><input type="checkbox" defaultChecked /> Investment-Deck</label><br/>
<label><input type="checkbox" defaultChecked /> Valuation-Report</label><br/>
<label><input type="checkbox" defaultChecked /> Due-Diligence Report</label><br/>
<label><input type="checkbox" defaultChecked /> Market-Entry Strategy</label><br/>
<label><input type="checkbox" defaultChecked /> Competitive-Analysis</label><br/>
<label><input type="checkbox" defaultChecked /> Feasibility-Study</label><br/>
<label><input type="checkbox" defaultChecked /> Business-Valuation</label><br/>
<label><input type="checkbox" defaultChecked /> Franchise-Consultation</label><br/>
<label><input type="checkbox" defaultChecked /> Licensing-Strategy</label><br/>
<label><input type="checkbox" defaultChecked /> Merger-& Acquisition Support</label><br/>
<label><input type="checkbox" defaultChecked /> Crowdfunding-Campaign</label><br/>
<label><input type="checkbox" defaultChecked /> ICO-Whitepaper</label><br/>
<label><input type="checkbox" defaultChecked /> Tokenomics-Design</label><br/>
<label><input type="checkbox" defaultChecked /> NFT-Project Launch</label><br/>
<label><input type="checkbox" defaultChecked /> Discord-Community Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Telegram-Community Mgmt</label><br/>
<label><input type="checkbox" defaultChecked /> Twitter-Community Mgmt</label><br/>
<label><input type="checkbox" defaultChecked /> Reddit-Community Mgmt</label><br/>
<label><input type="checkbox" defaultChecked /> Forum-Moderation</label><br/>
<label><input type="checkbox" defaultChecked /> Influencer-Out 2D-Animation</label><br/>
<label><input type="checkbox" defaultChecked /> 3D-Animation</label><br/>
<label><input type="checkbox" defaultChecked /> Whiteboard-Animation</label><br/>
<label><input type="checkbox" defaultChecked /> Podcast-Editing</label><br/>
<label><input type="checkbox" defaultChecked /> Audio-Mastering</label><br/>
<label><input type="checkbox" defaultChecked /> Music-Production</label><br/>
<label><input type="checkbox" defaultChecked /> Sound-Effects Design</label><br/>
<label><input type="checkbox" defaultChecked /> Virtual-Assistant</label><br/>
<label><input type="checkbox" defaultChecked /> Data-Entry</label><br/>
<label><input type="checkbox" defaultChecked /> Web-Research</label><br/>
<label><input type="checkbox" defaultChecked /> Lead-Generation</label><br/>
<label><input type="checkbox" defaultChecked /> CRM-Setup & Cleanup</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Research</label><br/>
<label><input type="checkbox" defaultChecked /> Market-Research</label><br/>
<label><input type="checkbox" defaultChecked /> Competitive-Analysis</label><br/>
<label><input type="checkbox" defaultChecked /> Business-Plan Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Pitch-Deck Creation</label><br/>
<label><input type="checkbox" defaultChecked /> Financial-Modeling</label><br/>
<label><input type="checkbox" defaultChecked /> Excel-Expert Services</label><br/>
<label><input type="checkbox" defaultChecked /> PowerPoint-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Presentation-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Infographic-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Resume-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Cover-Letter Writing</label><br/>
<label><input type="checkbox" defaultChecked /> LinkedIn-Profile Makeover</label><br/>
<label><input type="checkbox" defaultChecked /> Career-Coaching</label><br/>
<label><input type="checkbox" defaultChecked /> Interview-Prep</label><br/>
<label><input type="checkbox" defaultChecked /> Public-Speaking Coach</label><br/>
<label><input type="checkbox" defaultChecked /> Life-Coaching</label><br/>
<label><input type="checkbox" defaultChecked /> Stress-Management Coach</label><br/>
<label><input type="checkbox" defaultChecked /> Time-Management Coach</label><br/>
<label><input type="checkbox" defaultChecked /> Nutrition-Coach</label><br/>
<label><input type="checkbox" defaultChecked /> Fitness-Coach (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Yoga-Instructor (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Meditation-Coach (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Diet-Planning (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Meal-Planning (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Recipe-Development</label><br/>
<label><input type="checkbox" defaultChecked /> Cooking-Class (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Baking-Class (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Cake-Decorating Class</label><br/>
<label><input type="checkbox" defaultChecked /> Chocolate-Making Class</label><br/>
<label><input type="checkbox" defaultChecked /> Cocktail-Mixing Class</label><br/>
<label><input type="checkbox" defaultChecked /> Barista-Training (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Wine-Tasting Host (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Art-Class (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Drawing-Class (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Painting-Class (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Calligraphy-Class (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Pottery-Class (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Sculpture-Class (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Music-Theory Class</label><br/>
<label><input type="checkbox" defaultChecked /> Guitar-Lessons (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Piano-Lessons (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Violin-Lessons (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Drums-Lessons (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Singing-Lessons (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> DJ-Training (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Music-Production (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Beat-Making (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Song-Writing (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Voice-Over Coaching</label><br/>
<label><input type="checkbox" defaultChecked /> Podcast-Launch Service</label><br/>
<label><input type="checkbox" defaultChecked /> Podcast-Management</label><br/>
<label><input type="checkbox" defaultChecked /> Audiobook-Narration</label><br/>
<label><input type="checkbox" defaultChecked /> Audiobook-Editing</label><br/>
<label><input type="checkbox" defaultChecked /> Soundtrack-Composition</label><br/>
<label><input type="checkbox" defaultChecked /> Jingle-Creation</label><br/>
<label><input type="checkbox" defaultChecked /> FX & Sound-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Audio-Restoration</label><br/>
<label><input type="checkbox" defaultChecked /> Noise-Reduction Service</label><br/>
<label><input type="checkbox" defaultChecked /> Mixing & Mastering</label><br/>
<label><input type="checkbox" defaultChecked /> Loop & Sample-Pack Creation</label><br/>
<label><input type="checkbox" defaultChecked /> Royalty-Free Music</label><br/>
<label><input type="checkbox" defaultChecked /> Stock-Music Production</label><br/>
<label><input type="checkbox" defaultChecked /> Custom-Song Gift</label><br/>
<label><input type="checkbox" defaultChecked /> Birthday-Song Recording</label><br/>
<label><input type="checkbox" defaultChecked /> Wedding-Song Composition</label><br/>
<label><input type="checkbox" defaultChecked /> Corporate-Anthem Creation</label><br/>
<label><input type="checkbox" defaultChecked /> Voice-Mail Recording</label><br/>
<label><input type="checkbox" defaultChecked /> IVR-Prompt Recording</label><br/>
<label><input type="checkbox" defaultChecked /> Translation (All Languages)</label><br/>
<label><input type="checkbox" defaultChecked /> Proofreading (All Languages)</label><br/>
<label><input type="checkbox" defaultChecked /> Subtitling (All Languages)</label><br/>
<label><input type="checkbox" defaultChecked /> Transcription (All Languages)</label><br/>
<label><input type="checkbox" defaultChecked /> Interpretation (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Live-Captioning (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Sign-Language Interpretation</label><br/>
<label><input type="checkbox" defaultChecked /> Braille-Translation</label><br/>
<label><input type="checkbox" defaultChecked /> Audio-Description Creation</label><br/>
<label><input type="checkbox" defaultChecked /> Speech-Therapy (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Language-Therapy (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Dyslexia-Coaching (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> ADHD-Coaching (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Autism-Support (Online)</label><br/>
<label><input type="checkbox" defaultChecked /> Special-Needs Tutor</label><br/>
<label><input type="checkbox" defaultChecked /> Gifted-Child Mentor</label><br/>
<label><input type="checkbox" defaultChecked /> Homeschooling Consult</label><br/>
<label><input type="checkbox" defaultChecked /> Curriculum-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Lesson-Plan Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Educational-Content Creation</label><br/>
<label><input type="checkbox" defaultChecked /> Interactive-Content Design</label><br/>
<label><input type="checkbox" defaultChecked /> Gamification Consult</label><br/>
<label><input type="checkbox" defaultChecked /> Quiz & Test Creation</label><br/>
<label><input type="checkbox" defaultChecked /> Flashcard Creation</label><br/>
<label><input type="checkbox" defaultChecked /> Study-Guide Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Cheat-Sheet Design</label><br/>
<label><input type="checkbox" defaultChecked /> Calculator-App Creation</label><br/>
<label><input type="checkbox" defaultChecked /> Formula-Sheet Design</label><br/>
<label><input type="checkbox" defaultChecked /> Lab-Report Template</label><br/>
<label><input type="checkbox" defaultChecked /> Thesis-Template Design</label><br/>
<label><input type="checkbox" defaultChecked /> Presentation-Template</label><br/>
<label><input type="checkbox" defaultChecked /> Poster-Template Design</label><br/>
<label><input type="checkbox" defaultChecked /> Infographic-Template</label><br/>
<label><input type="checkbox" defaultChecked /> Certificate-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Diploma-Design</label><br/>
<label><input type="checkbox" defaultChecked /> ID-Card Design</label><br/>
<label><input type="checkbox" defaultChecked /> Business-Card Design</label><br/>
<label><input type="checkbox" defaultChecked /> Letterhead Design</label><br/>
<label><input type="checkbox" defaultChecked /> Envelope Design</label><br/>
<label><input type="checkbox" defaultChecked /> Folder Design</label><br/>
<label><input type="checkbox" defaultChecked /> Notebook Cover Design</label><br/>
<label><input type="checkbox" defaultChecked /> Calendar Design</label><br/>
<label><input type="checkbox" defaultChecked /> Planner Design</label><br/>
<label><input type="checkbox" defaultChecked /> Journal Design</label><br/>
<label><input type="checkbox" defaultChecked /> Coloring-Book Design</label><br/>
<label><input type="checkbox" defaultChecked /> Activity-Book Design</label><br/>
<label><input type="checkbox" defaultChecked /> Story-Book Illustration</label><br/>
<label><input type="checkbox" defaultChecked /> Comic-Book Creation</label><br/>
<label><input type="checkbox" defaultChecked /> Manga-Style Drawing</label><br/>
<label><input type="checkbox" defaultChecked /> Cartoon-Style Drawing</label><br/>
<label><input type="checkbox" defaultChecked /> Realistic-Portrait Drawing</label><br/>
<label><input type="checkbox" defaultChecked /> Caricature Drawing</label><br/>
<label><input type="checkbox" defaultChecked /> Digital-Portrait Painting</label><br/>
<label><input type="checkbox" defaultChecked /> Oil-Painting Portrait</label><br/>
<label><input type="checkbox" defaultChecked /> Watercolor Portrait</label><br/>
<label><input type="checkbox" defaultChecked /> Pencil-Portrait Drawing</label><br/>
<label><input type="checkbox" defaultChecked /> Charcoal-Portrait Drawing</label><br/>
<label><input type="checkbox" defaultChecked /> Pastel-Portrait Drawing</label><br/>
<label><input type="checkbox" defaultChecked /> Ink-Portrait Drawing</label><br/>
<label><input type="checkbox" defaultChecked /> Mixed-Media Portrait</label><br/>
<label><input type="checkbox" defaultChecked /> Collage-Portrait</label><br/>
<label><input type="checkbox" defaultChecked /> Mosaic-Portrait</label><br/>
<label><input type="checkbox" defaultChecked /> Sculpture-Portrait</label><br/>
<label><input type="checkbox" defaultChecked /> 3D-Printed Portrait</label><br/>
<label><input type="checkbox" defaultChecked /> NFT-Portrait Creation</label><br/>
<label><input type="checkbox" defaultChecked /> Crypto-Art Consult</label><br/>
<label><input type="checkbox" defaultChecked /> Blockchain-Consult</label><br/>
<label><input type="checkbox" defaultChecked /> Smart-Contract Audit</label><br/>
<label><input type="checkbox" defaultChecked /> DeFi-Protocol Consult</label><br/>
<label><input type="checkbox" defaultChecked /> ICO-Whitepaper Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Tokenomics-Design</label><br/>
<label><input type="checkbox" defaultChecked /> NFT-Collection Launch</label><br/>
<label><input type="checkbox" defaultChecked /> Metaverse-Consult</label><br/>
<label><input type="checkbox" defaultChecked /> VR-App Development</label><br/>
<label><input type="checkbox" defaultChecked /> AR-Filter Creation</label><br/>
<label><input type="checkbox" defaultChecked /> AR-App Development</label><br/>
<label><input type="checkbox" defaultChecked /> MR-App Development</label><br/>
<label><input type="checkbox" defaultChecked /> 360-Video Production</label><br/>
<label><input type="checkbox" defaultChecked /> Virtual-Tour Creation</label><br/>
<label><input type="checkbox" defaultChecked /> Digital-Twin Creation</label><br/>
<label><input type="checkbox" defaultChecked /> IoT-App Development</label><br/>
<label><input type="checkbox" defaultChecked /> Embedded-Systems</label><br/>
<label><input type="checkbox" defaultChecked /> PCB-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Circuit-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Firmware-Development</label><br/>
<label><input type="checkbox" defaultChecked /> RTOS-Development</label><br/>
<label><input type="checkbox" defaultChecked /> DSP-Programming</label><br/>
<label><input type="checkbox" defaultChecked /> FPGA-Development</label><br/>
<label><input type="checkbox" defaultChecked /> CPLD-Development</label><br/>
<label><input type="checkbox" defaultChecked /> VHDL-Programming</label><br/>
<label><input type="checkbox" defaultChecked /> Verilog-Programming</label><br/>
<label><input type="checkbox" defaultChecked /> SystemVerilog-Programming</label><br/>
<label><input type="checkbox" defaultChecked /> MATLAB-Programming</label><br/>
<label><input type="checkbox" defaultChecked /> Simulink-Modeling</label><br/>
<label><input type="checkbox" defaultChecked /> LabVIEW-Programming</label><br/>
<label><input type="checkbox" defaultChecked /> Python-Automation</label><br/>
<label><input type="checkbox" defaultChecked /> RPA-Development</label><br/>
<label><input type="checkbox" defaultChecked /> Selenium-Automation</label><br/>
<label><input type="checkbox" defaultChecked /> BeautifulSoup-Scraping</label><br/>
<label><input type="checkbox" defaultChecked /> Scrapy-Scraping</label><br/>
<label><input type="checkbox" defaultChecked /> API-Integration</label><br/>
<label><input type="checkbox" defaultChecked /> Webhook-Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Zapier-Automation</label><br/>
<label><input type="checkbox" defaultChecked /> Make-Automation</label><br/>
<label><input type="checkbox" defaultChecked /> n8n-Automation</label><br/>
<label><input type="checkbox" defaultChecked /> Microsoft-Power-Automate</label><br/>
<label><input type="checkbox" defaultChecked /> Google-Apps-Script</label><br/>
<label><input type="checkbox" defaultChecked /> Excel-VBA-Programming</label><br/>
<label><input type="checkbox" defaultChecked /> Access-Database Design</label><br/>
<label><input type="checkbox" defaultChecked /> SQL-Database Design</label><br/>
<label><input type="checkbox" defaultChecked /> MySQL-Administration</label><br/>
<label><input type="checkbox" defaultChecked /> PostgreSQL-Administration</label><br/>
<label><input type="checkbox" defaultChecked /> MongoDB-Administration</label><br/>
<label><input type="checkbox" defaultChecked /> Redis-Administration</label><br/>
<label><input type="checkbox" defaultChecked /> Cassandra-Administration</label><br/>
<label><input type="checkbox" defaultChecked /> Elasticsearch-Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Kibana-Dashboard Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Logstash-Pipeline Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Beats-Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Grafana-Dashboard Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Prometheus-Setup</label><br/>
<label><input type="checkbox" defaultChecked /> InfluxDB-Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Telegraf-Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Chronograf-Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Kapacitor-Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Tableau-Dashboard Setup</label><br/>
<label><input type="checkbox" defaultChecked /> PowerBI-Dashboard Setup</label><br/>
<label><input type="checkbox" defaultChecked /> QlikSense-Dashboard Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Looker-Studio Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Data-Visualization</label><br/>
<label><input type="checkbox" defaultChecked /> Data-Analysis</label><br/>
<label><input type="checkbox" defaultChecked /> Statistical-Analysis</label><br/>
<label><input type="checkbox" defaultChecked /> Animation-2D</label><br/>
<label><input type="checkbox" defaultChecked /> Animation-3D</label><br/>
<label><input type="checkbox" defaultChecked /> Whiteboard-Animation</label><br/>
<label><input type="checkbox" defaultChecked /> Podcast-Editing</label><br/>
<label><input type="checkbox" defaultChecked /> Audio-Mastering</label><br/>
<label><input type="checkbox" defaultChecked /> Music-Composition</label><br/>
<label><input type="checkbox" defaultChecked /> Jingle-Production</label><br/>
<label><input type="checkbox" defaultChecked /> Sound-Effects Design</label><br/>
<label><input type="checkbox" defaultChecked /> Virtual-Assistant</label><br/>
<label><input type="checkbox" defaultChecked /> Data-Entry</label><br/>
<label><input type="checkbox" defaultChecked /> Web-Research</label><br/>
<label><input type="checkbox" defaultChecked /> Lead-Generation</label><br/>
<label><input type="checkbox" defaultChecked /> CRM-Setup & Cleanup</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Research</label><br/>
<label><input type="checkbox" defaultChecked /> Data-Analysis</label><br/>
<label><input type="checkbox" defaultChecked /> Excel-Expert Services</label><br/>
<label><input type="checkbox" defaultChecked /> Google-Sheets Expert</label><br/>
<label><input type="checkbox" defaultChecked /> PowerPoint-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Canva-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Photo-Editing</label><br/>
<label><input type="checkbox" defaultChecked /> Image-Retouching</label><br/>
<label><input type="checkbox" defaultChecked /> Background-Removal</label><br/>
<label><input type="checkbox" defaultChecked /> Infographic-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Presentation-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Pitch-Deck Design</label><br/>
<label><input type="checkbox" defaultChecked /> Report-Design</label><br/>
<label><input type="checkbox" defaultChecked /> E-Book Formatting</label><br/>
<label><input type="checkbox" defaultChecked /> Kindle Formatting</label><br/>
<label><input type="checkbox" defaultChecked /> Print-On-Demand Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Amazon-KDP Setup</label><br/>
<label><input type="checkbox" defaultChecked /> Legal-Document Drafting</label><br/>
<label><input type="checkbox" defaultChecked /> Contract-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Terms-of-Service Drafting</label><br/>
<label><input type="checkbox" defaultChecked /> Privacy-Policy Drafting</label><br/>
<label><input type="checkbox" defaultChecked /> Business-Plan Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Pitch-Deck Creation</label><br/>
<label><input type="checkbox" defaultChecked /> Grant-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Policy-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Technical-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Medical-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> SEO-Content Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Sales-Copy Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Email-Copy Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Newsletter-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Press-Release Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Speech-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Proofreading & Editing</label><br/>
<label><input type="checkbox" defaultChecked /> Translation</label><br/>
<label><input type="checkbox" defaultChecked /> Transcription</label><br/>
<label><input type="checkbox" defaultChecked /> Subtitling & Captioning</label><br/>
<label><input type="checkbox" defaultChecked /> Voice-Over Recording</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Tutoring (All Subjects)</label><br/>
<label><input type="checkbox" defaultChecked /> Interview-Prep Coach</label><br/>
<label><input type="checkbox" defaultChecked /> CV/Resume Writing</label><br/>
<label><input type="checkbox" defaultChecked /> LinkedIn-Makeover</label><br/>
<label><input type="checkbox" defaultChecked /> Public-Speaking Coach</label><br/>
<label><input type="checkbox" defaultChecked /> Language-Conversation Partner</label><br/>
<label><input type="checkbox" defaultChecked /> Career-Counselling (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Life-Coaching (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Business-Coaching (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Financial-Planning (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Tax-Consultation (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Investment-Consultation (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Crypto-Consultation (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> NFT-Consultation</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Therapy (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Counselling (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Psychology (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Psychiatry (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Nutritionist (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Dietitian (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Fitness-Trainer (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Yoga-Instructor (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Pilates-Instructor (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Meditation-Coach (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Music-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Art-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Cooking-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Dance-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Singing-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Guitar-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Piano-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Violin-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Drum-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-DJ-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Production-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Music-Theory (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Songwriting (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Audio-Engineering (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Mixing-Mastering (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Beat-Making (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Sound-Design (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Foley-Artist (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Voice-Over-Coaching (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Singing-Coaching (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Speech-Therapy (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Language-Therapy (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Autism-Support (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Special-Needs-Tutor (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Qur’an-Tajweed (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Islamic-Studies (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Arabic-Calligraphy (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Fashion-Design (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Sewing-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Knitting-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Crochet-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Embroidery-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Jewelry-Making (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Pottery-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Candle-Making (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Soap-Making (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Perfume-Making (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Chocolate-Making (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Cake-Decorating (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Baking-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Cooking-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Sushi-Making (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Pizza-Making (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Bread-Making (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Pastry-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Cocktail-Making (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Barista-Training (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Wine-Tasting (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Cheese-Tasting (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Gardening-Lessons (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Plant-Care (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Bonsai-Training (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Hydroponic-Training (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Composting-Training (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Sustainability-Coach (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Zero-Waste-Coach (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Meditation-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Mindfulness-Coach (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Breathwork-Facilitator (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Reiki-Master (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Tarot-Reader (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Astrology-Reading (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Numerology-Reading (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Palm-Reading (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Crystal-Healing (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Chakra-Balancing (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Aroma-Therapy (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Herbal-Consult (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Naturopathy (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Ayurveda-Consult (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Homeopathy (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Nutritionist (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Dietitian (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Fitness-Coach (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Yoga-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Pilates-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Barre-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Zumba-Instructor (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Dance-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Ballet-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Hip-Hop-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Salsa-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Tango-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Belly-Dance-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Dabke-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Singing-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Guitar-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Piano-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Violin-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Drum-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Oud-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Qanun-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Ney-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Buzuq-Teacher (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Music-Theory (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Songwriting (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Beat-Making (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Mixing-Mastering (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Audio-Engineering (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Sound-Design (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Foley-Artist (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Voice-Over-Coaching (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Singing-Coaching (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Speech-Therapy (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Language-Therapy (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Autism-Support (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Special-Needs-Tutor (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Art-Therapy (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Music-Therapy (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Dance-Therapy (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Drama-Therapy (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Play-Therapy (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Counselling (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Psychology (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Psychiatry (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Therapy (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Animation-2D</label><br/>  
<label><input type="checkbox" defaultChecked /> Animation-3D</label><br/>
<label><input type="checkbox" defaultChecked /> Whiteboard-Animation</label><br/>
<label><input type="checkbox" defaultChecked /> Podcast-Editing</label><br/>
<label><input type="checkbox" defaultChecked /> Audio-Mastering</label><br/>
<label><input type="checkbox" defaultChecked /> Music-Composition</label><br/>
<label><input type="checkbox" defaultChecked /> Sound-Effects Design</label><br/>
<label><input type="checkbox" defaultChecked /> Online-Tutoring (All Subjects)</label><br/>
<label><input type="checkbox" defaultChecked /> Proofreading & Editing</label><br/>
<label><input type="checkbox" defaultChecked /> Legal-Consultation (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Financial-Consultation (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Tax-Consultation (Zoom)</label><br/>
<label><input type="checkbox" defaultChecked /> Business-Plan Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Pitch-Deck Creation</label><br/>
<label><input type="checkbox" defaultChecked /> Grant-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Policy-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Technical-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Medical-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Research-Paper Writing</label><br/>
<label><input type="checkbox" defaultChecked /> Data-Analysis (SPSS, R, Python)</label><br/>
<label><input type="checkbox" defaultChecked /> Survey-Design</label><br/>
<label><input type="checkbox" defaultChecked /> Market-Research Report</label><br/>
<label><input type="checkbox" defaultChecked /> Competitor-Analysis</label><br/>
<label><input type="checkbox" defaultChecked /> Brand-Strategy Consult</label><br/>
<label><input type="checkbox" defaultChecked /> UX-Audit & Recommendations</label><br/>
<label><input type="checkbox" defaultChecked /> Accessibility-Audit (WCAG)</label><br/>
<label><input type="checkbox" defaultChecked /> Privacy-Policy Drafting</label><br/>
<label><input type="checkbox" defaultChecked /> Terms-of-Service Drafting</label><br/>
<label><input type="checkbox" defaultChecked /> Cookie-Policy Drafting</label><br/>
<label><input type="checkbox" defaultChecked /> Return-Policy Drafting</label><br/>
<label><input type="checkbox" defaultChecked /> EULA Drafting</label><br/>
<label><input type="checkbox" defaultChecked /> SLA Drafting</label><br/>
<label><input type="checkbox" defaultChecked /> Contract-Writing</label><br/>
<label><input type="checkbox" defaultChecked /> NDA Drafting</label><br/>
<label><input type="checkbox" defaultChecked /> Employment-Contract</label><br/>
<label><input type="checkbox" defaultChecked /> Freelancer-Agreement</label><br/>
<label><input type="checkbox" defaultChecked /> Partnership-Agreement</label><br/>
<label><input type="checkbox"
      <button onClick={()=>alert('Categories saved')}>Save</button>

      <h2>3. Payment – Wish-Money QR</h2>
      <input type="file" accept="image/*" onChange={saveQr} />
      {qr && <img src={qr} width="200" alt="QR preview" />}
    </div>
  );
}
